// Generated by Wrangler by running `wrangler types`

interface Env {
	NEXT_PUBLIC_API_BASE_URL: "http://localhost:8787" | "https://github-app-backend.your-subdomain.workers.dev" | "https://github-app-backend-staging.your-subdomain.workers.dev";
	ENVIRONMENT: "development" | "production" | "staging";
	NEXT_PUBLIC_GITHUB_APP_NAME: "online-dev-team";
	NEXTJS_ENV: string;
}
